owner: storestpos
repo: uptime

sites:
  - name: Storest
    url: https://api.storest.io/health

status-website:
  cname: status.storest.io
  logoUrl: https://app.storest.io/assets/icon.svg
  name: Storest
  introTitle: "This is a title."
  introMessage: "Helping your business grow."
