owner: storestpos
repo: uptime

sites:
  - name: Storest
    url: https://api.storest.io/health

status-website:
  cname: status.storest.io
  logoUrl: https://avatars.githubusercontent.com/u/104506618
  name: Storest
  introTitle: "This is a title."
  introMessage: "Helping your business grow."
