owner: storestpos
repo: upptime

sites:
  - name: Storest
    url: https://api.storest.io/health

status-website:
  cname: status.storest.io
  logoUrl: https://www.storest.io/assets/icon.svg
  name: Storest
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Helping your business grow.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
